AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - '**/Gemfile'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - 'spec/fixtures/**/*'
    - config/initializers/*.rb
    - 'tmp/**/*'
    - db/migrate/*
    - bin/*
    - config/*
    - config/environments/*
    - spec/rails_helper.rb
    - 'spec/mailers/previews/*'
  TargetRubyVersion: 2.7.0
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/requests/**/*.rb'
    - 'spec/models/*.rb'
    - 'spec/policies/*'
    - 'spec/factories/*'
    - 'spec/factories/payroll/*'
    - 'spec/mailers/*.rb'
Metrics/ClassLength:
  Max: 100
Style/Lambda:
  Enabled: false
