version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: ./
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
