---
swagger: '2.0'
info:
  title: shortl API
basePath: "/api/v1"
paths:
  "/links":
    post:
      summary: Generates a shortened URL
      tags:
      - Links
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: url
        in: query
        type: string
        required: true
      responses:
        '201':
          description: returns body for successful shortening
        '400':
          description: returns error for unsuccessful shortening
